### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by oatmealproblem** [wcember/pypub#1]
The link to the documentation in the readme is broken.

**Comment by wcember** [comment]
Hey man. Thanks for the note. Documentation doesn't exist yet but I am working on it.

How did you find the repository? Are you interested in it? I haven't thoroughly tested the code and the most recent commit is mid converting over a dependency from lxml to beautifulsoup

**Comment by oatmealproblem** [comment]
I found it on pypi, searching for epub libraries. Abstracting the details of the epub specification and the permissive license attracted me to yours.

I'm looking for something a bit more stable though. Good luck!
