### ISSUE TITLE
Entity 'nbsp' not defined

### ISSUE THREAD

**Issue by marcogoldin** [wcember/pypub#4]
Hi, i got this message opening the rendered epub file 

> "This page contains the following errors:
> error on line 35 at column 15: Entity 'nbsp' not defined
> Below is a rendering of the page up to the first error."

Any suggestions for stripping out the tag?
Thank you, great work with pypub, really.

**Comment by wcember** [comment]
Hi Marco - I pushed through a fix on Github and uploaded a new version to PyPI. Can you try repulling?
